#!/user/bin/env ansible-playbook
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  tasks:
    - name: install nginx
      dnf: 
        name: nginx
        update_cache: yes

      - name: create nginx sites-available dir
        file: 
          path: /etc/nginx/sites-available
          state: directory
          recurse: yes
       
      - name: create nginx sites-enabled dir
        file: 
          path: /etc/nginx/sites-enabled
          state: directory
          recurse: yes

      - name: copy nginx config file
        copy: 
          src: files/nginx.conf
          dest: /etc/nginx/sites-available/default

      - name: enable configuration
        file:
          dest: /etc/nginx/sites-enabled/default
          src: /etc/nginx/sites-available/default
          state: link
      
      - name: copy index.html
        template: 
          src: templates/index.html.j2
          dest: /usr/share/nginx/html/index.html
          mode: 0644

      - name: restart nginx
        service: 
          name: nginx
          state: restarted

